import React, { useState } from "react";
import { AccordionDemo } from "./Accordian";

const accordions = [
  {
    id: 1,
    title: "It turned out to be the Hope Diamond?",
    content:
      "Imagine reaching deep inside you for all the strength and wisdom that you need to make this decision today. As you do so, imagine that when you choose to make that decision that deep inside your mind you are switching off the alternative path.",
  },
  {
    id: 2,
    title: "Why do stars twinkle at night?",
    content:
      "Stars twinkle because of the Earth's atmosphere. As starlight passes through layers of air with varying temperatures and densities, the light bends and creates the twinkling effect we see.",
  },
  {
    id: 3,
    title: "What makes the ocean blue?",
    content:
      "The ocean appears blue because water absorbs colors in the red part of the light spectrum and reflects the blue wavelengths back to our eyes.",
  },
  {
    id: 4,
    title: "How does a compass work?",
    content:
      "A compass works because of Earth's magnetic field. The needle aligns itself with the magnetic field, pointing toward the magnetic poles.",
  },
  {
    id: 5,
    title: "Can plants communicate?",
    content:
      "Yes, plants can communicate through chemical signals. For example, when under attack, some plants release chemicals to warn nearby plants of potential danger.",
  },
  {
    id: 6,
    title: "What causes lightning?",
    content:
      "Lightning occurs due to the buildup of electrical charges in clouds. When the charge difference becomes large enough, it results in a rapid discharge, creating a lightning bolt.",
  },
  {
    id: 7,
    title: "Why do we dream?",
    content:
      "Dreams are believed to be a way for the brain to process emotions, memories, and information. They occur during the REM (rapid eye movement) stage of sleep.",
  },
  {
    id: 8,
    title: "How do airplanes stay in the air?",
    content:
      "Airplanes stay in the air because of lift, which is generated by the wings as air flows over them. The shape of the wings helps create a pressure difference that keeps the plane aloft.",
  },
];

export default function Faq() {
  const [openItem, setOpenItem] = useState(null); // Manage state of which accordion item is open

  return (
    <div className="flex w-[80%] flex-col items-center justify-center gap-5">
      <div className="flex items-center justify-center gap-2">
        <img src="subtitle-icon.png" alt="" className="h-5 w-5" />
        <span className="text-2xl font-extrabold text-primary">FAQ</span>
      </div>

      <h1 className="text-2xl font-extrabold sm:text-4xl lg:text-6xl">
        Frequently Asked Questions
      </h1>
      <div className="w-full">
        <AccordionDemo />
      </div>
    </div>
  );
}
